version: '3.8'

services:
  recipe-app-next-client-test:
    image: recipe-app-next-client-test
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: test.Dockerfile
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-test
    depends_on:
      - postgres

  recipe-app-java-backend-test:
    image: recipe-app-java-backend-test
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 8000:8080
    container_name: recipe-app-java-backend-test
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432