version: '3.8'

services:
  recipe-app-next-client-prod:
    image: recipe-app-next-client-prod
    environment:
      - NEXTAUTH_SECRET=secretkey
      - NEXT_APP_API_URL=http://recipe-app-backend-prod:8080
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-prod

  recipe-app-backend-prod:
    image: recipe-app-backend-prod
    env_file:
      - server_nextjs/.env
    build:
      context: server_nextjs
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-backend-prod

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin