version: '3.8'

services:
  recipe-app-next-client:
    image: recipe-app-next-client
    environment:
      # - NEXTAUTH_URL=http://recipe-app-java-backend:8080
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres?schema=public
    build:
      context: ./nextjs-client
      dockerfile: dev.Dockerfile
    volumes:
      - ./nextjs-client/src:/usr/src/app/src
    ports:
      - 3000:3000
    container_name: recipe-app-next-client
    depends_on:
      - postgres

  recipe-app-java-backend:
    image: recipe-app-java-backend
    build:
      context: ./java-backend
      dockerfile: Dockerfile
    ports:
      - 8000:8080
    container_name: recipe-app-java-backend
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
    #volumes:
    #  - ./prisma/migrations/generated/migration.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin