services:
  recipe-app-next-client-prod:
    image: recipe-app-next-client-prod
    environment:
      - NEXTAUTH_SECRET=secretkey
      - NEXT_APP_API_URL=http://recipe-app-backend-prod:8080
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-prod

  recipe-app-backend-prod:
    image: recipe-app-backend-prod
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file: 
      # Create .env file in the ./server directory with the following content:
      # DATABASE_URL=[JDBC URL]
      # DATABASE_USERNAME=[POSTGRES USERNAME]
      # DATABASE_PASSWORD=[POSTGRES PASSWORD]
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-backend-prod