version: '3.8'

services:
  recipe-app-next-client-test:
    image: recipe-app-next-client-test
    environment:
      - NEXTAUTH_SECRET=secretkey
      - NEXT_APP_API_URL=http://recipe-app-backend-test:8080
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-test
    depends_on:
      - recipe-app-backend-test

  recipe-app-backend-test:
    image: recipe-app-backend-test
    environment:
      - SPRING_PROFILES_ACTIVE=test
      - DATABASE_URL=jdbc:postgresql://postgres:5432/postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
    build:
      context: ./server
      dockerfile: test.Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-backend-test
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
