services:
  recipe-app-next-client-dev:
    image: recipe-app-next-client-dev
    environment:
      - NEXTAUTH_SECRET=secretkey
      - NEXT_APP_API_URL=http://recipe-app-backend-dev:8080
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-dev

  recipe-app-backend-dev:
    image: recipe-app-backend-dev
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    build:
      context: ./server
      dockerfile: dev.Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-backend-dev
    volumes:
      - ./server/src/main:/app/src/main
    restart: always