version: '3.8'

services:
  recipe-app-test:
    image: recipe-app-test
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres_test?schema=public
      - APP_ENV=test # Used for Cypress testing since NODE_ENV is set to production
    build:
      context: ./
      dockerfile: test.Dockerfile
    volumes:
      - ./src:/usr/src/app/src
    ports:
      - 3000:3000
    container_name: recipe-app-test
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres_test
    ports:
      - 5432:5432
    volumes:
      - ./prisma/migrations/generated/migration.sql:/docker-entrypoint-initdb.d/init.sql
