version: '3.8'

services:
  recipe-app-next-client-test:
    image: recipe-app-next-client-test
    environment:
      - NEXTAUTH_SECRET=secretkey
      - NEXT_APP_API_URL=http://recipe-app-backend-test:8080
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: recipe-app-next-client-test

  recipe-app-backend-test:
    image: recipe-app-backend-test
    environment:
      - DATABASE_PORT=5432
      - DATABASE_HOST=postgres
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=postgres
      - JWT_SECRET_KEY=secret
    build:
      context: ./server
      dockerfile: test.Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-backend-test

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432