version: '3.8'

services:
  recipe-app-next-client:
    image: recipe-app-next-client
    env_file:
      - ./client/.env
    build:
      context: ./client
      dockerfile: dev.Dockerfile
    volumes:
      - ./client/src:/usr/src/app/src
    ports:
      - 3000:3000
    container_name: recipe-app-next-client
    depends_on:
      - postgres

  recipe-app-java-backend:
    image: recipe-app-java-backend
    env_file:
      - ./server/.env
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    container_name: recipe-app-java-backend
    volumes:
      - ./server/src:/usr/src/app/src
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - 5432:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin