# fly.toml file generated for recipeapp-pro on 2023-10-29T14:49:12+02:00

app = "recipeapp-pro"
kill_signal = "SIGINT"
kill_timeout = 5
mounts = []
processes = []

[[services]]
  internal_port = 3000
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
  
  # [deploy]
  #  release_command = "npx prisma db deploy"
